### PR TITLE
Update forge to 1865 and latest mappings

### PR DESCRIPTION
**Pull request by jriwanek**

### CODE REVIEW

**Comment by hea3ven** [comment]
I've merged it manualy: 2630a90

**Comment by jriwanek** [comment]
Any particular reason why 1860 instead of 1865?

also, I forgot to include the matching gradle wrapper jar, I can send that in another PR if you need me to.

**Comment by hea3ven** [comment]
Because the mod adds the configured forge version as a mod dependency, so I always keep it to the minimum version required, and 1860 is the one that fixes the issues with the mappings. It just gives the users more flexibility to choose the forge version.
Sure, make another PR.

**Comment by jriwanek** [comment]
I'll get on that in the morning, Thanks for the feedback though.

**Pull request closed without merging**
